export interface Country {
  name: string;
  code: string;
  phoneCode: string;
}

export const countries: Country[] = [
  { name: 'Afganistán', code: 'AF', phoneCode: '+93' },
  { name: 'Albania', code: 'AL', phoneCode: '+355' },
  { name: 'Alemania', code: 'DE', phoneCode: '+49' },
  { name: 'Andorra', code: 'AD', phoneCode: '+376' },
  { name: 'Angola', code: 'AO', phoneCode: '+244' },
  { name: 'Antigua y Barbuda', code: 'AG', phoneCode: '+1' },
  { name: 'Arabia Saudita', code: 'SA', phoneCode: '+966' },
  { name: 'Argelia', code: 'DZ', phoneCode: '+213' },
  { name: 'Argentina', code: 'AR', phoneCode: '+54' },
  { name: 'Armenia', code: 'AM', phoneCode: '+374' },
  { name: 'Australia', code: 'AU', phoneCode: '+61' },
  { name: 'Austria', code: 'AT', phoneCode: '+43' },
  { name: 'Azerbaiyán', code: 'AZ', phoneCode: '+994' },
  { name: 'Bahamas', code: 'BS', phoneCode: '+1' },
  { name: 'Bangladés', code: 'BD', phoneCode: '+880' },
  { name: 'Barbados', code: 'BB', phoneCode: '+1' },
  { name: 'Baréin', code: 'BH', phoneCode: '+973' },
  { name: 'Bélgica', code: 'BE', phoneCode: '+32' },
  { name: 'Belice', code: 'BZ', phoneCode: '+501' },
  { name: 'Benín', code: 'BJ', phoneCode: '+229' },
  { name: 'Bielorrusia', code: 'BY', phoneCode: '+375' },
  { name: 'Birmania', code: 'MM', phoneCode: '+95' },
  { name: 'Bolivia', code: 'BO', phoneCode: '+591' },
  { name: 'Bosnia y Herzegovina', code: 'BA', phoneCode: '+387' },
  { name: 'Botsuana', code: 'BW', phoneCode: '+267' },
  { name: 'Brasil', code: 'BR', phoneCode: '+55' },
  { name: 'Brunéi', code: 'BN', phoneCode: '+673' },
  { name: 'Bulgaria', code: 'BG', phoneCode: '+359' },
  { name: 'Burkina Faso', code: 'BF', phoneCode: '+226' },
  { name: 'Burundi', code: 'BI', phoneCode: '+257' },
  { name: 'Bután', code: 'BT', phoneCode: '+975' },
  { name: 'Cabo Verde', code: 'CV', phoneCode: '+238' },
  { name: 'Camboya', code: 'KH', phoneCode: '+855' },
  { name: 'Camerún', code: 'CM', phoneCode: '+237' },
  { name: 'Canadá', code: 'CA', phoneCode: '+1' },
  { name: 'Catar', code: 'QA', phoneCode: '+974' },
  { name: 'Chad', code: 'TD', phoneCode: '+235' },
  { name: 'Chile', code: 'CL', phoneCode: '+56' },
  { name: 'China', code: 'CN', phoneCode: '+86' },
  { name: 'Chipre', code: 'CY', phoneCode: '+357' },
  { name: 'Colombia', code: 'CO', phoneCode: '+57' },
  { name: 'Comoras', code: 'KM', phoneCode: '+269' },
  { name: 'Corea del Norte', code: 'KP', phoneCode: '+850' },
  { name: 'Corea del Sur', code: 'KR', phoneCode: '+82' },
  { name: 'Costa de Marfil', code: 'CI', phoneCode: '+225' },
  { name: 'Costa Rica', code: 'CR', phoneCode: '+506' },
  { name: 'Croacia', code: 'HR', phoneCode: '+385' },
  { name: 'Cuba', code: 'CU', phoneCode: '+53' },
  { name: 'Dinamarca', code: 'DK', phoneCode: '+45' },
  { name: 'Dominica', code: 'DM', phoneCode: '+1' },
  { name: 'Ecuador', code: 'EC', phoneCode: '+593' },
  { name: 'Egipto', code: 'EG', phoneCode: '+20' },
  { name: 'El Salvador', code: 'SV', phoneCode: '+503' },
  { name: 'Emiratos Árabes Unidos', code: 'AE', phoneCode: '+971' },
  { name: 'Eritrea', code: 'ER', phoneCode: '+291' },
  { name: 'Eslovaquia', code: 'SK', phoneCode: '+421' },
  { name: 'Eslovenia', code: 'SI', phoneCode: '+386' },
  { name: 'España', code: 'ES', phoneCode: '+34' },
  { name: 'Estados Unidos', code: 'US', phoneCode: '+1' },
  { name: 'Estonia', code: 'EE', phoneCode: '+372' },
  { name: 'Etiopía', code: 'ET', phoneCode: '+251' },
  { name: 'Filipinas', code: 'PH', phoneCode: '+63' },
  { name: 'Finlandia', code: 'FI', phoneCode: '+358' },
  { name: 'Fiyi', code: 'FJ', phoneCode: '+679' },
  { name: 'Francia', code: 'FR', phoneCode: '+33' },
  { name: 'Gabón', code: 'GA', phoneCode: '+241' },
  { name: 'Gambia', code: 'GM', phoneCode: '+220' },
  { name: 'Georgia', code: 'GE', phoneCode: '+995' },
  { name: 'Ghana', code: 'GH', phoneCode: '+233' },
  { name: 'Granada', code: 'GD', phoneCode: '+1' },
  { name: 'Grecia', code: 'GR', phoneCode: '+30' },
  { name: 'Guatemala', code: 'GT', phoneCode: '+502' },
  { name: 'Guinea', code: 'GN', phoneCode: '+224' },
  { name: 'Guinea Ecuatorial', code: 'GQ', phoneCode: '+240' },
  { name: 'Guinea-Bisáu', code: 'GW', phoneCode: '+245' },
  { name: 'Guyana', code: 'GY', phoneCode: '+592' },
  { name: 'Haití', code: 'HT', phoneCode: '+509' },
  { name: 'Honduras', code: 'HN', phoneCode: '+504' },
  { name: 'Hungría', code: 'HU', phoneCode: '+36' },
  { name: 'India', code: 'IN', phoneCode: '+91' },
  { name: 'Indonesia', code: 'ID', phoneCode: '+62' },
  { name: 'Irak', code: 'IQ', phoneCode: '+964' },
  { name: 'Irán', code: 'IR', phoneCode: '+98' },
  { name: 'Irlanda', code: 'IE', phoneCode: '+353' },
  { name: 'Islandia', code: 'IS', phoneCode: '+354' },
  { name: 'Islas Marshall', code: 'MH', phoneCode: '+692' },
  { name: 'Islas Salomón', code: 'SB', phoneCode: '+677' },
  { name: 'Israel', code: 'IL', phoneCode: '+972' },
  { name: 'Italia', code: 'IT', phoneCode: '+39' },
  { name: 'Jamaica', code: 'JM', phoneCode: '+1' },
  { name: 'Japón', code: 'JP', phoneCode: '+81' },
  { name: 'Jordania', code: 'JO', phoneCode: '+962' },
  { name: 'Kazajistán', code: 'KZ', phoneCode: '+7' },
  { name: 'Kenia', code: 'KE', phoneCode: '+254' },
  { name: 'Kirguistán', code: 'KG', phoneCode: '+996' },
  { name: 'Kiribati', code: 'KI', phoneCode: '+686' },
  { name: 'Kuwait', code: 'KW', phoneCode: '+965' },
  { name: 'Laos', code: 'LA', phoneCode: '+856' },
  { name: 'Lesoto', code: 'LS', phoneCode: '+266' },
  { name: 'Letonia', code: 'LV', phoneCode: '+371' },
  { name: 'Líbano', code: 'LB', phoneCode: '+961' },
  { name: 'Liberia', code: 'LR', phoneCode: '+231' },
  { name: 'Libia', code: 'LY', phoneCode: '+218' },
  { name: 'Liechtenstein', code: 'LI', phoneCode: '+423' },
  { name: 'Lituania', code: 'LT', phoneCode: '+370' },
  { name: 'Luxemburgo', code: 'LU', phoneCode: '+352' },
  { name: 'Macedonia del Norte', code: 'MK', phoneCode: '+389' },
  { name: 'Madagascar', code: 'MG', phoneCode: '+261' },
  { name: 'Malasia', code: 'MY', phoneCode: '+60' },
  { name: 'Malaui', code: 'MW', phoneCode: '+265' },
  { name: 'Maldivas', code: 'MV', phoneCode: '+960' },
  { name: 'Malí', code: 'ML', phoneCode: '+223' },
  { name: 'Malta', code: 'MT', phoneCode: '+356' },
  { name: 'Marruecos', code: 'MA', phoneCode: '+212' },
  { name: 'Mauricio', code: 'MU', phoneCode: '+230' },
  { name: 'Mauritania', code: 'MR', phoneCode: '+222' },
  { name: 'México', code: 'MX', phoneCode: '+52' },
  { name: 'Micronesia', code: 'FM', phoneCode: '+691' },
  { name: 'Moldavia', code: 'MD', phoneCode: '+373' },
  { name: 'Mónaco', code: 'MC', phoneCode: '+377' },
  { name: 'Mongolia', code: 'MN', phoneCode: '+976' },
  { name: 'Montenegro', code: 'ME', phoneCode: '+382' },
  { name: 'Mozambique', code: 'MZ', phoneCode: '+258' },
  { name: 'Namibia', code: 'NA', phoneCode: '+264' },
  { name: 'Nauru', code: 'NR', phoneCode: '+674' },
  { name: 'Nepal', code: 'NP', phoneCode: '+977' },
  { name: 'Nicaragua', code: 'NI', phoneCode: '+505' },
  { name: 'Níger', code: 'NE', phoneCode: '+227' },
  { name: 'Nigeria', code: 'NG', phoneCode: '+234' },
  { name: 'Noruega', code: 'NO', phoneCode: '+47' },
  { name: 'Nueva Zelanda', code: 'NZ', phoneCode: '+64' },
  { name: 'Omán', code: 'OM', phoneCode: '+968' },
  { name: 'Países Bajos', code: 'NL', phoneCode: '+31' },
  { name: 'Pakistán', code: 'PK', phoneCode: '+92' },
  { name: 'Palaos', code: 'PW', phoneCode: '+680' },
  { name: 'Panamá', code: 'PA', phoneCode: '+507' },
  { name: 'Papúa Nueva Guinea', code: 'PG', phoneCode: '+675' },
  { name: 'Paraguay', code: 'PY', phoneCode: '+595' },
  { name: 'Perú', code: 'PE', phoneCode: '+51' },
  { name: 'Polonia', code: 'PL', phoneCode: '+48' },
  { name: 'Portugal', code: 'PT', phoneCode: '+351' },
  { name: 'Reino Unido', code: 'GB', phoneCode: '+44' },
  { name: 'República Centroafricana', code: 'CF', phoneCode: '+236' },
  { name: 'República Checa', code: 'CZ', phoneCode: '+420' },
  { name: 'República del Congo', code: 'CG', phoneCode: '+242' },
  { name: 'República Democrática del Congo', code: 'CD', phoneCode: '+243' },
  { name: 'República Dominicana', code: 'DO', phoneCode: '+1' },
  { name: 'Ruanda', code: 'RW', phoneCode: '+250' },
  { name: 'Rumania', code: 'RO', phoneCode: '+40' },
  { name: 'Rusia', code: 'RU', phoneCode: '+7' },
  { name: 'Samoa', code: 'WS', phoneCode: '+685' },
  { name: 'San Cristóbal y Nieves', code: 'KN', phoneCode: '+1' },
  { name: 'San Marino', code: 'SM', phoneCode: '+378' },
  { name: 'San Vicente y las Granadinas', code: 'VC', phoneCode: '+1' },
  { name: 'Santa Lucía', code: 'LC', phoneCode: '+1' },
  { name: 'Santo Tomé y Príncipe', code: 'ST', phoneCode: '+239' },
  { name: 'Senegal', code: 'SN', phoneCode: '+221' },
  { name: 'Serbia', code: 'RS', phoneCode: '+381' },
  { name: 'Seychelles', code: 'SC', phoneCode: '+248' },
  { name: 'Sierra Leona', code: 'SL', phoneCode: '+232' },
  { name: 'Singapur', code: 'SG', phoneCode: '+65' },
  { name: 'Siria', code: 'SY', phoneCode: '+963' },
  { name: 'Somalia', code: 'SO', phoneCode: '+252' },
  { name: 'Sri Lanka', code: 'LK', phoneCode: '+94' },
  { name: 'Suazilandia', code: 'SZ', phoneCode: '+268' },
  { name: 'Sudáfrica', code: 'ZA', phoneCode: '+27' },
  { name: 'Sudán', code: 'SD', phoneCode: '+249' },
  { name: 'Sudán del Sur', code: 'SS', phoneCode: '+211' },
  { name: 'Suecia', code: 'SE', phoneCode: '+46' },
  { name: 'Suiza', code: 'CH', phoneCode: '+41' },
  { name: 'Surinam', code: 'SR', phoneCode: '+597' },
  { name: 'Tailandia', code: 'TH', phoneCode: '+66' },
  { name: 'Tanzania', code: 'TZ', phoneCode: '+255' },
  { name: 'Tayikistán', code: 'TJ', phoneCode: '+992' },
  { name: 'Timor Oriental', code: 'TL', phoneCode: '+670' },
  { name: 'Togo', code: 'TG', phoneCode: '+228' },
  { name: 'Tonga', code: 'TO', phoneCode: '+676' },
  { name: 'Trinidad y Tobago', code: 'TT', phoneCode: '+1' },
  { name: 'Túnez', code: 'TN', phoneCode: '+216' },
  { name: 'Turkmenistán', code: 'TM', phoneCode: '+993' },
  { name: 'Turquía', code: 'TR', phoneCode: '+90' },
  { name: 'Tuvalu', code: 'TV', phoneCode: '+688' },
  { name: 'Ucrania', code: 'UA', phoneCode: '+380' },
  { name: 'Uganda', code: 'UG', phoneCode: '+256' },
  { name: 'Uruguay', code: 'UY', phoneCode: '+598' },
  { name: 'Uzbekistán', code: 'UZ', phoneCode: '+998' },
  { name: 'Vanuatu', code: 'VU', phoneCode: '+678' },
  { name: 'Vaticano', code: 'VA', phoneCode: '+379' },
  { name: 'Venezuela', code: 'VE', phoneCode: '+58' },
  { name: 'Vietnam', code: 'VN', phoneCode: '+84' },
  { name: 'Yemen', code: 'YE', phoneCode: '+967' },
  { name: 'Yibuti', code: 'DJ', phoneCode: '+253' },
  { name: 'Zambia', code: 'ZM', phoneCode: '+260' },
  { name: 'Zimbabue', code: 'ZW', phoneCode: '+263' },
];
